id: I8B6D4FB1
default_language: zh
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-08 15:25:44.452972
last_modified: 2023-02-08 15:25:44.453107
source_metadata:
  title: Tathāgatagarbhasūtra
  language: zh
bases:
  B45A:
    base_file: B45A.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
